name = "my-remix-app"
account_id = "a79c627cd7928a81f58db010c83560b0"
workers_dev = true
compatibility_date = "2024-09-23"

main = "./build/server/index.js"

[site]
bucket = "./build/client"

[build]
command = "npm run build"

compatibility_flags = ["nodejs_compat"]

# Ensure Cloudflare Pages recognizes this configuration
pages_build_output_dir = "./build/client"