name = "my-remix-app"
type = "javascript"

account_id = "a79c627cd7928a81f58db010c83560b0"
workers_dev = true
compatibility_date = "2023-10-01"

[site]
bucket = "./public"
entry-point = "./build"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"
pages_build_output_dir = "./build"